### ISSUE TITLE
Start running the pipeline?

### ISSUE THREAD

**Issue by DanielSprockett** [CUMoellerLab/sn-mg-pipeline#19]
I think once we get the MinHashing merged, this pipeline might be mature enough to start processing the samples. What do you think about me starting it sometime soon? That way at least we can get things QC'ed while we work on the assembly/binning steps.

Are there any advantages to waiting and running it all at once?

**Comment by tanaes** [comment]
Sorry for the delay! I feel like things are up and running pretty well. I've incorporated all the suggestions for the Sourmash profiling, so we should be good to go.

Unless there were some major overhaul in the output file structure, it will be pretty straightforward to add new rules/outputs!

**Comment by DanielSprockett** [comment]
Ok, great! I'll start this running on the BioHPC server sometime soon. I'm thinking about setting the number of cores for the snakemake command to 16, but let me know if I should change that.
