### ISSUE TITLE
Host removal options?

### ISSUE THREAD

**Issue by tanaes** [CUMoellerLab/sn-mg-pipeline#3]
In [the old code](https://github.com/tanaes/Moeller_lab_Snakemake_tutorial/blob/5ead9b6f9be8401651c86b97d69c2a4c29fdbb20/Snakefile#L94) I used in our Snakemake workshop, we had manually specified output flag filtering to capture as many *possibly* human reads as possible, in the interest of privacy for human subjects research. 

In the case of this pipeline, though, perhaps we want the filter to be a little less restrictive? According to [this paper](https://www.microbiologyresearch.org/docserver/fulltext/mgen/6/7/mgen000393.pdf?expires=1614634314&id=id&accname=guest&checksum=F5730B798C82B6A9903F9ACB92D3B079), Bowtie2 using "default parameters" performs pretty well in terms of capturing true positives, and has a very low false-positive rate (i.e. flagging bacterial reads as human). For our purposes, that seems actually preferable -- filtering out parts of bacterial genomes will result in broken assemblies, and we really probably mostly care about the easily-mapped regions of the host genome anyway. 

This will also greatly simplify the code. Thoughts?

**Comment by DanielSprockett** [comment]
So, you're talking about just removing the `--very-sensitive` parameter from the mapping? I'm totally fine with that. Thanks for sharing that paper! That makes a lot of sense. 

For my purposes (and I think for most of the projects that are currently going on in the lab),  a few host reads that get missed would likely end up in smaller assemblies that won't factor much into the analysis anyway.

**Comment by tanaes** [comment]
We can basically replace *all* the code with a single line: 

`bowtie2 -p 8 -x GRCh38_noalt_as -1 SAMPLE_R1.fastq.gz -2 SAMPLE_R2.fastq.gz --un-conc-gz SAMPLE_host_removed > SAMPLE_mapped_and_unmapped.sam` (as in [this example](http://www.metagenomics.wiki/tools/short-read/remove-host-sequences)). And we can pipe that sam alignment directly to samtools to get only the aligned host reads. Nice!

**Comment by DanielSprockett** [comment]
Sounds great! I'll close this issue then.
