### ISSUE TITLE
TODO: change database downloads to optionally take local filepaths

### ISSUE THREAD

**Issue by tanaes** [CUMoellerLab/sn-mg-pipeline#32]
- [ ] metaphplan DB download
- [ ] host genome download and index

Should be able to have a filepath in config and check if it's valid, and if so, use it
if it's not a valid filepath, then download the database (so for host genome, GCA84298591845.1 is not going to be a valid filepath, so then assume it's NCBI searchable)

**Comment by DanielSprockett** [comment]
Resolved in #46
