### ISSUE TITLE
Prototype Selection: num_prototypes

### ISSUE THREAD

**Issue by DanielSprockett** [CUMoellerLab/sn-mg-pipeline#8]
What do you think is the optimal way to select the number of prototypes to select? Will this be constant, say...5% of the total number of samples? 

It could also vary based on the variance of the total sample set. We could write a `while` loop that just keeps picking more and more prototypes until the variance in the prototype set is within some cut off of the variance in the entire dataset. 

 Or should it be more informed by the binning approach? 

Are there other things we should consider?

**Comment by tanaes** [comment]
Prototype selection is a relatively lightweight task once the DMs are computed; the algorithm Stefan wrote was made to handle 100s of 1000s of genomes. So a valid strategy might be to by default compute a few levels for each sample set, which could then be used as inputs to downstream analyses depending on desired resource expenditures.

**Comment by DanielSprockett** [comment]
Ok, great! That makes sense. 

I know I won't have much time to work on this for a while, but as I sit here holding a sleeping baby, I was curious how one would go about using the prototype selection python script (or any other piece of software that isn't available as a wrapper or in conda) in a snakemake workflow.

Do you write a rule that just uses wget or something to download it off github? Or do you have to somehow put it into a conda repository, so that the link is more permanent?

**Comment by DanielSprockett** [comment]
I think we've addressed this now as well. The pipeline outputs every number of prototypes, and each user can simply select a number that works for them.
